name: Get last 2 most recent workflow logs

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: List workflow runs
      run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.TOKEN_ACTIONS_PYTHON }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=2 -o recent.json

    - name: Store most recent workflow run ID
      id: workflow1
      run: echo "id1=$(cat recent.json | jq ".workflow_runs[0].id")" >> "$GITHUB_OUTPUT"

    - name: Store most recent workflow run ID
      id: workflow2
      run: echo "id2=$(cat recent.json | jq ".workflow_runs[1].id")" >> "$GITHUB_OUTPUT"

    - name: Get most recent workflow run ID
      run: echo "${{ steps.workflow1.outputs.id1 }}, ${{ steps.workflow2.outputs.id2 }}"


      
        