name: Test workflow for artifacts

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: get artifacts
      id: get-artifact
      uses: MichaelMelena/list-artifacts@v1.0.1
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN_ACTIONS_PYTHON }}

    - run: echo ${{ secrets.TOKEN_ACTIONS_PYTHON }}


      
        