name: Python artifact

on:
  workflow_run:
    workflows: [ Python unit test ]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Get an artifact
      run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer <YOUR-TOKEN>"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/mdlewis33/actions-python/actions/artifacts/721720687
