name: Test workflow

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      FILE_NAME: results.json

    steps:
    - uses: actions/checkout@v2

    - name: get artifacts
      id: result
      uses: MichaelMelena/list-artifacts@v1.0.1
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN_ACTIONS_PYTHON }}
        repository: ${{ github.repository }}
    - run: |
        ${{ steps.result.outputs.artifacts }} > $FILE_NAME

    - name: Commit and push to GitHub
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add ./artifacts/$FILE_NAME
        timestamp=$(date -u)
        git commit -m "Latest artifacts: ${timestamp}" || exit 0
        git push
        